version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
      - "4500:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
    volumes:
      - ./:/app
